var order = {
    init: function (params) {
    	app.crud.initEditDialog({});
        app.crud.initCRUDBtn({
        	add:function(){
        	},
        	update:function(){
        	}
        });
    	app.crud.initViewList({
       	 	columns:[[
       		        {field:'ck',checkbox:true},
					{field:'orderCode',title:'订单编号(年月日+两位流水）',width:100,align:'center'},
					{field:'customerId',title:'客户',width:100,align:'center'},
					{field:'productId',title:'产品',width:100,align:'center'},
					{field:'propertyId',title:'抵押房产',width:100,align:'center'},
					{field:'bankId',title:'银行',width:100,align:'center'},
					{field:'branchId',title:'支行',width:100,align:'center'},
					{field:'signingDate',title:'签约日期（年月日）',width:100,align:'center'},
					{field:'estimateFinishTime',title:'预计完成日期（年月日）',width:100,align:'center'},
					{field:'loanAmount',title:'贷款金额（万元）',width:100,align:'center'},
					{field:'lendingRate',title:'月利率（厘/月）',width:100,align:'center'},
					{field:'loanTerm',title:'贷款年限',width:100,align:'center'},
					{field:'repayWayId',title:'还款方式',width:100,align:'center'},
					{field:'repayNote',title:'',width:100,align:'center'},
					{field:'serviceChargePercent',title:'手续费百分比（%）',width:100,align:'center'},
					{field:'serviceCharge',title:'手续费（元）',width:100,align:'center'},
					{field:'matchmakerId',title:'介绍人id',width:100,align:'center'},
					{field:'commissionAmount',title:'返佣金额',width:100,align:'center'},
					{field:'commissionRate',title:'返佣比例（%）',width:100,align:'center'},
					{field:'commissionReason',title:'返佣理由',width:100,align:'center'},
					{field:'csAssistantId',title:'客服助理',width:100,align:'center'},
					{field:'csPrincipalId',title:'客服负责人',width:100,align:'center'},
					{field:'followUserId',title:'跟单人',width:100,align:'center'},
					{field:'ownerId',title:'拥有人',width:100,align:'center'},
					{field:'processInstanceId',title:'',width:100,align:'center'},
					{field:'auditStatus',title:'审核状态（1草稿2审核中3审核通过4重新调整5放弃6审核不通过）',width:100,align:'center'},
					{field:'status',title:'状态（1已立项2已签约3已放款4完结）',width:100,align:'center'},
					{field:'cost',title:'订单成本（元）',width:100,align:'center'},
					{field:'receiveAmount',title:'应收金额（元）',width:100,align:'center'},
					{field:'payAmount',title:'应付金额（元）',width:100,align:'center'},
					{field:'companyLoanAmount',title:'借款总金额（万元）',width:100,align:'center'},
					{field:'companyLoanInterest',title:'借款利息总额（元）',width:100,align:'center'},
					{field:'receivablesAccountStatus',title:'收款账户审核状态（1草稿2审核中3审核通过4审核不通过）',width:100,align:'center'},
					{field:'loanDate',title:'放款日期',width:100,align:'center'},
					{field:'loanMoney',title:'放款金额',width:100,align:'center'},
					{field:'settlementCharge',title:'结算手续费',width:100,align:'center'},
					{field:'settlementClerk',title:'结算员',width:100,align:'center'},
					{field:'settlementSubmitDate',title:'结算提交时间',width:100,align:'center'},
					{field:'settlementSubmitUserId',title:'结算提交人Id',width:100,align:'center'},
					{field:'settlementAuditStatus',title:'结算审核状态（1草稿2审核中3审核通过4审核不通过）',width:100,align:'center'},
					{field:'brokerageAuditStatus',title:'佣金审核状态（1草稿2审核中3审核通过4审核不通过）',width:100,align:'center'},
					{field:'brokerageGrantState',title:'佣金发放状态',width:100,align:'center'},
					{field:'brokerageTotal',title:'佣金总额',width:100,align:'center'},
					{field:'id',hidden:true}
       		]]
    	});
    }
}
